#!/usr/bin/env python3
"""Generate the immutable C suffix table from the vendored Yomichan rules."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RULES = {"v1": 1, "v5": 2, "vs": 4, "vk": 8, "vz": 16, "adj-i": 32, "iru": 64}


def generate():
    data = json.loads((ROOT / "third_party/yomichan/deinflect.json").read_text())
    lines = ["/* Generated by tools/gen_deinflect.py; Yomichan GPL-3.0 rules.",
             " * See third_party/yomichan/README.md. Do not edit by hand. */",
             "static const DeinflectRule deinflect_rules[] = {"]
    for rules in data.values():
        for rule in rules:
            source, target = rule["kanaIn"], rule["kanaOut"]
            flags = [sum(RULES[r] for r in rule[key]) for key in ("rulesIn", "rulesOut")]
            lines.append('    {%s, %s, %d, %d, %d, %d},' % (
                json.dumps(source, ensure_ascii=False), json.dumps(target, ensure_ascii=False),
                len(source.encode()), len(target.encode()), *flags))
    return "\n".join([*lines, "};", ""])


if __name__ == "__main__":
    (ROOT / "core/deinflect.inc").write_text(generate(), encoding="utf-8")
