#!/usr/bin/env python3
"""Generate the small CP932 character mapping; no fonts or game assets."""
from pathlib import Path
import hashlib
import struct

def generate():
    values = []
    for lead in list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD)):
        for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFD)):
            try:
                char = bytes((lead, trail)).decode("cp932")
                cp = ord(char) if len(char) == 1 else 0
            except UnicodeDecodeError:
                cp = 0
            values.append(cp)
    digest = hashlib.sha256(struct.pack("<" + "H" * len(values), *values)).hexdigest()
    rows = ["/* Generated by tools/generate_cp932.py (Python CP932 codec).",
            f" * Little-endian uint16 mapping SHA-256: {digest} */",
            "static const uint16_t cp932_pairs[11280] = {"]
    rows += ["    " + ",".join(f"0x{x:04X}" for x in values[i:i+16]) + ","
             for i in range(0, len(values), 16)]
    rows += ["};", ""]
    return "\n".join(rows)

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    target = Path(__file__).resolve().parent.parent / "core/cp932_table.inc"
    expected = generate()
    if args.check:
        if target.read_text() != expected:
            raise SystemExit("CP932 table differs from the generator")
    else:
        target.write_text(expected)
